=== PabloMateosP/BDsms/Actividad2_Simil/ConcesionarioMoto.dtd
<!ELEMENT ConcesionarioMoto (Moto*)>
<!ELEMENT Moto (Marca,Modelo,Matrícula,Potencia,Cilindrada)>
<!ELEMENT Marca (#PCDATA)>
<!ELEMENT Modelo (#PCDATA)>
<!ELEMENT Matrícula (#PCDATA)>
<!ELEMENT Potencia (#PCDATA)>
<!ELEMENT Cilindrada (#PCDATA)>

=== PabloMateosP/BDsms/Actividad2_Simil/ConcesionarioMoto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE Concesionario SYSTEM "ConcesionarioMoto.dtd"> -->
<ConcesionarioMoto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConcesionarioMotoSchema.xsd">
    <Moto>
        <Marca>Aprilia</Marca>
        <Modelo>RSV4</Modelo>
        <Matrícula>1434 SPQ</Matrícula>
        <Potencia>217</Potencia>
        <Cilindrada>1099cc</Cilindrada>
    </Moto>
    <Moto>
        <Marca>Aprilia</Marca>
        <Modelo>RSV4 Factory</Modelo>
        <Matrícula>3362 XSQ</Matrícula>
        <Potencia>217</Potencia>
        <Cilindrada>1099cc</Cilindrada>
    </Moto>
    <Moto>
        <Marca>BMW</Marca>
        <Modelo>S 1000 RR</Modelo>
        <Matrícula>3452 KJD</Matrícula>
        <Potencia>207</Potencia>
        <Cilindrada>999cc</Cilindrada>
    </Moto>
    <Moto>
        <Marca>BMW</Marca>
        <Modelo>M 1000 RR</Modelo>
        <Matrícula>9796 YQY</Matrícula>
        <Potencia>212</Potencia>
        <Cilindrada>999cc</Cilindrada>
    </Moto>
    <Moto>
        <Marca>Ducati</Marca>
        <Modelo>Panigale V4 S/SP</Modelo>
        <Matrícula>3213 RTQ</Matrícula>
        <Potencia>214</Potencia>
        <Cilindrada>1103cc</Cilindrada>
    </Moto>
</ConcesionarioMoto>
