=== PabloMateosP/BDsms/Editorial/Editorial.dtd
<!ELEMENT Informe (Cabecera, Tabla)>
<!ELEMENT Cabecera (titulo, contenido, descripcion, fecha)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT Tabla (region+, trimestre, libros_vendidos)>
<!ELEMENT region (Norte | Centro | Sur)>
<!ELEMENT Norte (#PCDATA| trimestreTabla | librosvendidos)*>
<!ELEMENT Centro (#PCDATA| trimestreTabla | librosvendidos)*>
<!ELEMENT Sur (#PCDATA| trimestreTabla | librosvendidos)*>
<!ELEMENT trimestreTabla (#PCDATA)>
<!ELEMENT librosvendidos (#PCDATA)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT libros_vendidos (#PCDATA)>

=== PabloMateosP/BDsms/Editorial/Editorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Informe SYSTEM "editorial.dtd">
<Informe>
  <Cabecera>
    <titulo>Ediciones Aranda</titulo>
    <contenido>Informe regional del ventas</contenido>
    <descripcion>Descripcion: informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    <fecha>Fecha: 30/12/2009</fecha>
  </Cabecera>
  <Tabla>
    <region>
      <Norte>Norte
        <trimestreTabla>1</trimestreTabla>
        <librosvendidos>24000</librosvendidos>
        <trimestreTabla>2</trimestreTabla>
        <librosvendidos>38600</librosvendidos>
        <trimestreTabla>3</trimestreTabla>
        <librosvendidos>NO_INFO</librosvendidos>
        <trimestreTabla>4trimestreTabla</trimestreTabla>
        <librosvendidos>NO_INFO</librosvendidos>
      </Norte>
    </region>
    <region>
      <Centro>Centro
        <trimestreTabla>1</trimestreTabla>
        <librosvendidos>NO_INFO</librosvendidos>
        <trimestreTabla>2</trimestreTabla>
        <librosvendidos>16080</librosvendidos>
        <trimestreTabla>3</trimestreTabla>
        <librosvendidos>25000</librosvendidos>
        <trimestreTabla>4</trimestreTabla>
        <librosvendidos>29000</librosvendidos>
      </Centro>
    </region>
    <region>
      <Sur>Sur
        <trimestreTabla>1</trimestreTabla>
        <librosvendidos>27000</librosvendidos>
        <trimestreTabla>2</trimestreTabla>
        <librosvendidos>31400</librosvendidos>
        <trimestreTabla>3</trimestreTabla>
        <librosvendidos>40100</librosvendidos>
        <trimestreTabla>4</trimestreTabla>
        <librosvendidos>30000</librosvendidos>
      </Sur>
    </region>
    <trimestre>Trimestre</trimestre>
    <libros_vendidos>Libros vendidos</libros_vendidos>
  </Tabla>
</Informe>
